/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Addr, Uint128, InstantiateMsg, Coin, ExecuteMsg, Binary, QueryMsg, Asset, ArrayOfAsset, ChannelDetails, String, ArrayOfChannelDetails, ChannelConractConfig, Boolean, ArrayOfString, Playlist, ArrayOfPlaylist } from "./OmniFlixChannel.types";
export interface OmniFlixChannelMsg {
  contractAddress: string;
  sender: string;
  pause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpause: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  setPausers: ({
    pausers
  }: {
    pausers: string[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  publish: ({
    assetOnftCollectionId,
    assetOnftId,
    channelId,
    isVisible,
    playlistName,
    salt
  }: {
    assetOnftCollectionId: string;
    assetOnftId: string;
    channelId: string;
    isVisible: boolean;
    playlistName?: string;
    salt: Binary;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unpublish: ({
    channelId,
    publishId
  }: {
    channelId: string;
    publishId: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  assetSetDetails: ({
    channelId,
    isVisible,
    publishId
  }: {
    channelId: string;
    isVisible: boolean;
    publishId: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  playlistCreate: ({
    channelId,
    playlistName
  }: {
    channelId: string;
    playlistName: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  playlistDelete: ({
    channelId,
    playlistName
  }: {
    channelId: string;
    playlistName: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  playlistAddAsset: ({
    assetChannelId,
    channelId,
    playlistName,
    publishId
  }: {
    assetChannelId: string;
    channelId: string;
    playlistName: string;
    publishId: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  playlistRemoveAsset: ({
    channelId,
    playlistName,
    publishId
  }: {
    channelId: string;
    playlistName: string;
    publishId: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  playlistRefresh: ({
    channelId,
    playlistName
  }: {
    channelId: string;
    playlistName: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  createChannel: ({
    collabarators,
    description,
    salt,
    userName
  }: {
    collabarators?: string[];
    description: string;
    salt: Binary;
    userName: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  setChannelDetails: ({
    channelId,
    description
  }: {
    channelId: string;
    description: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  setConfig: ({
    admin,
    channelCreationFee,
    feeCollector
  }: {
    admin?: string;
    channelCreationFee?: Coin[];
    feeCollector?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class OmniFlixChannelMsgComposer implements OmniFlixChannelMsg {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.pause = this.pause.bind(this);
    this.unpause = this.unpause.bind(this);
    this.setPausers = this.setPausers.bind(this);
    this.publish = this.publish.bind(this);
    this.unpublish = this.unpublish.bind(this);
    this.assetSetDetails = this.assetSetDetails.bind(this);
    this.playlistCreate = this.playlistCreate.bind(this);
    this.playlistDelete = this.playlistDelete.bind(this);
    this.playlistAddAsset = this.playlistAddAsset.bind(this);
    this.playlistRemoveAsset = this.playlistRemoveAsset.bind(this);
    this.playlistRefresh = this.playlistRefresh.bind(this);
    this.createChannel = this.createChannel.bind(this);
    this.setChannelDetails = this.setChannelDetails.bind(this);
    this.setConfig = this.setConfig.bind(this);
  }

  pause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {}
        })),
        funds: _funds
      })
    };
  };
  unpause = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpause: {}
        })),
        funds: _funds
      })
    };
  };
  setPausers = ({
    pausers
  }: {
    pausers: string[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_pausers: {
            pausers
          }
        })),
        funds: _funds
      })
    };
  };
  publish = ({
    assetOnftCollectionId,
    assetOnftId,
    channelId,
    isVisible,
    playlistName,
    salt
  }: {
    assetOnftCollectionId: string;
    assetOnftId: string;
    channelId: string;
    isVisible: boolean;
    playlistName?: string;
    salt: Binary;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          publish: {
            asset_onft_collection_id: assetOnftCollectionId,
            asset_onft_id: assetOnftId,
            channel_id: channelId,
            is_visible: isVisible,
            playlist_name: playlistName,
            salt
          }
        })),
        funds: _funds
      })
    };
  };
  unpublish = ({
    channelId,
    publishId
  }: {
    channelId: string;
    publishId: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unpublish: {
            channel_id: channelId,
            publish_id: publishId
          }
        })),
        funds: _funds
      })
    };
  };
  assetSetDetails = ({
    channelId,
    isVisible,
    publishId
  }: {
    channelId: string;
    isVisible: boolean;
    publishId: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          asset_set_details: {
            channel_id: channelId,
            is_visible: isVisible,
            publish_id: publishId
          }
        })),
        funds: _funds
      })
    };
  };
  playlistCreate = ({
    channelId,
    playlistName
  }: {
    channelId: string;
    playlistName: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          playlist_create: {
            channel_id: channelId,
            playlist_name: playlistName
          }
        })),
        funds: _funds
      })
    };
  };
  playlistDelete = ({
    channelId,
    playlistName
  }: {
    channelId: string;
    playlistName: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          playlist_delete: {
            channel_id: channelId,
            playlist_name: playlistName
          }
        })),
        funds: _funds
      })
    };
  };
  playlistAddAsset = ({
    assetChannelId,
    channelId,
    playlistName,
    publishId
  }: {
    assetChannelId: string;
    channelId: string;
    playlistName: string;
    publishId: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          playlist_add_asset: {
            asset_channel_id: assetChannelId,
            channel_id: channelId,
            playlist_name: playlistName,
            publish_id: publishId
          }
        })),
        funds: _funds
      })
    };
  };
  playlistRemoveAsset = ({
    channelId,
    playlistName,
    publishId
  }: {
    channelId: string;
    playlistName: string;
    publishId: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          playlist_remove_asset: {
            channel_id: channelId,
            playlist_name: playlistName,
            publish_id: publishId
          }
        })),
        funds: _funds
      })
    };
  };
  playlistRefresh = ({
    channelId,
    playlistName
  }: {
    channelId: string;
    playlistName: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          playlist_refresh: {
            channel_id: channelId,
            playlist_name: playlistName
          }
        })),
        funds: _funds
      })
    };
  };
  createChannel = ({
    collabarators,
    description,
    salt,
    userName
  }: {
    collabarators?: string[];
    description: string;
    salt: Binary;
    userName: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_channel: {
            collabarators,
            description,
            salt,
            user_name: userName
          }
        })),
        funds: _funds
      })
    };
  };
  setChannelDetails = ({
    channelId,
    description
  }: {
    channelId: string;
    description: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_channel_details: {
            channel_id: channelId,
            description
          }
        })),
        funds: _funds
      })
    };
  };
  setConfig = ({
    admin,
    channelCreationFee,
    feeCollector
  }: {
    admin?: string;
    channelCreationFee?: Coin[];
    feeCollector?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_config: {
            admin,
            channel_creation_fee: channelCreationFee,
            fee_collector: feeCollector
          }
        })),
        funds: _funds
      })
    };
  };
}