/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
  accepted_tip_denoms: string[];
  admin: Addr;
  channel_creation_fee: Coin[];
  channels_collection_id: string;
  channels_collection_name: string;
  channels_collection_symbol: string;
  fee_collector: Addr;
  reserved_usernames: ReservedUsername[];
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface ReservedUsername {
  address?: string | null;
  username: string;
}
export type ExecuteMsg = {
  pause: {};
} | {
  unpause: {};
} | {
  set_pausers: {
    pausers: string[];
  };
} | {
  publish: {
    asset_source: AssetSource;
    channel_id: string;
    is_visible: boolean;
    playlist_name?: string | null;
    salt: Binary;
  };
} | {
  unpublish: {
    channel_id: string;
    publish_id: string;
  };
} | {
  asset_update_details: {
    channel_id: string;
    is_visible: boolean;
    publish_id: string;
  };
} | {
  playlist_create: {
    channel_id: string;
    playlist_name: string;
  };
} | {
  playlist_delete: {
    channel_id: string;
    playlist_name: string;
  };
} | {
  playlist_add_asset: {
    asset_channel_id: string;
    channel_id: string;
    playlist_name: string;
    publish_id: string;
  };
} | {
  playlist_remove_asset: {
    channel_id: string;
    playlist_name: string;
    publish_id: string;
  };
} | {
  playlist_refresh: {
    channel_id: string;
    playlist_name: string;
  };
} | {
  channel_create: {
    banner_picture?: string | null;
    channel_name: string;
    description?: string | null;
    payment_address: Addr;
    profile_picture?: string | null;
    salt: Binary;
    user_name: string;
  };
} | {
  channel_delete: {
    channel_id: string;
  };
} | {
  channel_update_details: {
    banner_picture?: string | null;
    channel_id: string;
    channel_name?: string | null;
    description?: string | null;
    payment_address?: string | null;
    profile_picture?: string | null;
  };
} | {
  set_config: {
    admin?: string | null;
    channel_creation_fee?: Coin[] | null;
    fee_collector?: string | null;
  };
} | {
  manage_reserved_usernames: {
    add_usernames?: ReservedUsername[] | null;
    remove_usernames?: string[] | null;
  };
} | {
  tip_creator: {
    amount: Coin;
    channel_id: string;
  };
} | {
  channel_add_collaborator: {
    channel_id: string;
    collaborator_address: string;
    collaborator_details: ChannelCollaborator;
  };
} | {
  channel_remove_collaborator: {
    channel_id: string;
    collaborator_address: string;
  };
} | {
  channel_follow: {
    channel_id: string;
  };
} | {
  channel_unfollow: {
    channel_id: string;
  };
};
export type AssetSource = {
  nft: {
    collection_id: string;
    onft_id: string;
  };
} | {
  off_chain: {
    description: string;
    media_uri: string;
    name: string;
  };
};
export type Binary = string;
export type Role = "admin" | "publisher" | "moderator";
export type Decimal = string;
export interface ChannelCollaborator {
  role: Role;
  share: Decimal;
}
export type QueryMsg = {
  is_paused: {};
} | {
  pausers: {};
} | {
  channel_details: {
    channel_id?: string | null;
    user_name?: string | null;
  };
} | {
  channel_metadata: {
    channel_id: string;
  };
} | {
  channels: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  channel_id: {
    user_name: string;
  };
} | {
  playlist: {
    channel_id: string;
    playlist_name: string;
  };
} | {
  playlists: {
    channel_id: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  config: {};
} | {
  assets: {
    channel_id: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  asset: {
    channel_id: string;
    publish_id: string;
  };
} | {
  reserved_usernames: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  get_channel_collaborator: {
    channel_id: string;
    collaborator_address: Addr;
  };
} | {
  get_channel_collaborators: {
    channel_id: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  followers_count: {
    channel_id: string;
  };
} | {
  followers: {
    channel_id: string;
    limit?: number | null;
    start_after?: string | null;
  };
};
export interface Asset {
  asset_source: AssetSource;
  channel_id: string;
  is_visible: boolean;
  publish_id: string;
}
export type ArrayOfAsset = Asset[];
export interface ChannelDetails {
  channel_id: string;
  onft_id: string;
  payment_address: Addr;
  user_name: string;
}
export type String = string;
export interface ChannelMetadata {
  banner_picture?: string | null;
  channel_name: string;
  description?: string | null;
  profile_picture?: string | null;
}
export type ArrayOfChannelDetails = ChannelDetails[];
export interface ChannelConractConfig {
  accepted_tip_denoms: string[];
  admin: Addr;
  channel_creation_fee: Coin[];
  channels_collection_id: string;
  channels_collection_name: string;
  channels_collection_symbol: string;
  fee_collector: Addr;
}
export type ArrayOfAddr = Addr[];
export type Uint64 = number;
export type ArrayOfTupleOfAddrAndChannelCollaborator = [Addr, ChannelCollaborator][];
export type Boolean = boolean;
export type ArrayOfString = string[];
export interface Playlist {
  assets: [string, string][];
  playlist_name: string;
}
export type ArrayOfPlaylist = Playlist[];
export type ArrayOfReservedUsername = ReservedUsername[];